CREATE TABLE users (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL, phone VARCHAR(30) NOT NULL, role ENUM('dealer','admin') NOT NULL DEFAULT 'dealer',
 is_active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE cars (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, owner_id INT UNSIGNED NOT NULL, created_by_id INT UNSIGNED NOT NULL,
 title VARCHAR(180) NOT NULL, brand VARCHAR(80) NOT NULL, model VARCHAR(100) NOT NULL, year SMALLINT UNSIGNED NOT NULL,
 price DECIMAL(12,2) NOT NULL, mileage INT UNSIGNED NULL, fuel_type VARCHAR(40) NOT NULL, transmission VARCHAR(40) NOT NULL,
 description TEXT NOT NULL, status ENUM('active','sold','draft') NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (owner_id) REFERENCES users(id), FOREIGN KEY (created_by_id) REFERENCES users(id),
 INDEX idx_car_filters (status, brand, year, transmission, price), INDEX idx_owner (owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE car_images (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, car_id INT UNSIGNED NOT NULL, image_path VARCHAR(255) NOT NULL,
 sort_order TINYINT UNSIGNED NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (car_id) REFERENCES cars(id) ON DELETE CASCADE, INDEX idx_car_images (car_id, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE inquiries (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, car_id INT UNSIGNED NOT NULL, buyer_id INT UNSIGNED NULL,
 buyer_name VARCHAR(120) NOT NULL, buyer_email VARCHAR(190) NOT NULL, buyer_phone VARCHAR(30) NOT NULL, message TEXT NOT NULL,
 notification_status ENUM('pending','sent','failed','not_configured') NOT NULL DEFAULT 'not_configured', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (car_id) REFERENCES cars(id) ON DELETE CASCADE, FOREIGN KEY (buyer_id) REFERENCES users(id) ON DELETE SET NULL,
 INDEX idx_car_inquiries (car_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
